version: 1

formatters:
  simple:
    format: '%(name)s - %(levelname)s - %(message)s'
  extended:
    format: '%(asctime)s - %(name)s - %(levelname)s - %(message)s'

handlers:
  console:
    class: logging.StreamHandler
    level: DEBUG
    formatter: simple

  file_handler:
    class: logging.FileHandler
    level: INFO
    filename: modelling.log
    formatter: extended

loggers:
  dev:
    handlers: [console, file_handler]
    propagate: no

root:
  handlers: [file_handler]